# Generated by Django 5.0.6 on 2026-05-26 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('collection', models.CharField(choices=[('schools', 'Schools'), ('classes', 'Classes'), ('subjects', 'Subjects'), ('topics', 'Topics'), ('assignments', 'Assignments'), ('submissions', 'Submissions'), ('attendance', 'Attendance'), ('users', 'Users'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('chats', 'Chats'), ('messages', 'Messages'), ('discussions', 'Discussions'), ('announcements', 'Announcements'), ('results', 'Results'), ('notifications', 'Notifications'), ('achievements', 'Achievements'), ('games', 'Games'), ('fees', 'Fees'), ('cbt_exams', 'Cbt Exams'), ('video_classes', 'Video Classes')], max_length=100)),
                ('document_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In Flight'), ('synced', 'Synced'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('client_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['client_timestamp'],
                'indexes': [models.Index(fields=['status', 'client_timestamp'], name='queue_app_s_status_4b5536_idx'), models.Index(fields=['collection', 'document_id'], name='queue_app_s_collect_b951fa_idx'), models.Index(fields=['user_id', 'status'], name='queue_app_s_user_id_9ff725_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='queue_app.syncoperation')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
